### ISSUE TITLE
Tried to install, but got an error

### ISSUE THREAD

**Issue by justin808** [lmmx/gdocs2md-html#3]
```
Access Not Configured. The API (Drive API) is not enabled for your project. Please use the Google Developers 
```

There's a message when you add the service for google drive

```
These services must also be enabled in the Google Developers Console.
```

But it's not clear where you do that.

I also have multiple google accounts, one personal, and one google apps.

Thanks for any assistance!

**Comment by lmmx** [comment]
Hey, sorry for the delay, check out [the install guide in the README](https://github.com/lmmx/gdocs2md-html#brief-installation) :smile: The "advanced Drive API" has to be enabled per script install at the minute - obviously this isn't ideal, if I find a minute I think it's mature enough to potentially register as an "app" (or something like that) so it could be used across projects, but it shouldn't take a minute to switch on that API in the meantime.

**Comment by katylava** [comment]
FYI, I had to also go to my Developer's console and enable the Drive API for this project. Just flipping the toggle in "Advanced Google Services" didn't work.
