### ISSUE TITLE
Global install or per document?

### ISSUE THREAD

**Issue by taylorjason** [lmmx/gdocs2md-html#7]
So to clarify does this script need to be set up for ever gdoc or can it be installed once and used on any google doc? I seem to have to run the setupScript function every time I reopen the same doc and I cannot get it to work on any doc other than the one I initially set it up on. Thanks!

**Comment by taylorjason** [comment]
To clarify I just noticed the > (once per doc) piece.

However I am still confused as to why the `Markdown` menu is not there every time I open the doc I have the script installed in.

**Comment by lmmx** [comment]
Hi Taylor, sorry for the late reply - hadn't seen this.

Yeah, has to be installed each time, it's not an "app" and I keep telling myself I'll find the time in between my studies to develop it into one (I also think it's possible to make it into a Chrome extension to keep it always in the menu).

I agree it'd make reuse much easier, and also possibly let you store settings that persist across sessions/documents.

Sorry for the inconvenience, but the preview box was a big step in making it more user friendly than when I found it (previously everything got emailed or sent to a folder in your Drive...)

This is definitely on my to do list, and if anyone can point me to some guides or has experience in this I'd love to hear it.
